# Override these values in another config file
# e.g.
#
# import config
# config.BOT_TOKEN = 'your_bot_token'

TESSERACT_OCR_PATH = ''

BOT_TOKEN = ''

# Member Tracking spreadsheet IDs
MEMBER_TRACKING_SPREADSHEET_ID = ''
MEMBER_TRACKING_SHEET_ID_MEMBER_LIST = 0
MEMBER_TRACKING_SHEET_ID_WEEKLY_PARTICIPATION = 0
MEMBER_TRACKING_SHEET_ID_PASTURE_PARTICIPATION = 0

# Boss Parties spreadsheet IDs
BOSS_PARTIES_SPREADSHEET_ID = ''
BOSS_PARTIES_SHEET_ID_MEMBERS = 0

# Grove submissions spreadsheet IDs
MEMBER_ACTIVITY_SPREADSHEET_ID = ''
MEMBER_ACTIVITY_SHEET_ID_ABSENCES = 0
MEMBER_ACTIVITY_SHEET_ID_BIRTHDAYS = 0

# Discord IDs
GROVE_GUILD_ID = 0

GROVE_CHANNEL_ID_LEADERBOARD = 0
GROVE_CHANNEL_ID_BOSSING_PARTIES = 0
GROVE_CHANNEL_ID_MEMBER_ACTIVITY = 0
GROVE_CHANNEL_ID_MEMBER_JOIN_LEAVE = 0
GROVE_CHANNEL_ID_MAPLE_CHAT = 0
GROVE_CHANNEL_ID_INTRODUCTIONS = 0
GROVE_CHANNEL_ID_GENERAL = 0

GROVE_ROLE_ID_BIRTHDAY = 0
GROVE_ROLE_ID_AWAY = 0
GROVE_ROLE_ID_JUNIOR = 0
GROVE_ROLE_ID_CELESTIAL = 0
GROVE_ROLE_ID_SPIRIT = 0
GROVE_ROLE_ID_TREE = 0
GROVE_ROLE_ID_SAPLING = 0
GROVE_ROLE_ID_MOSS = 0
GROVE_ROLE_ID_GROVE = 0
GROVE_ROLE_ID_BOSSING_GUEST = 0
GROVE_ROLE_ID_FRIEND = 0
GROVE_ROLE_ID_BOT = 0

GROVE_AUDIT_EXCEPTIONS = []
