# Override these values in another config file
# e.g.
#
# import config
# config.BOT_TOKEN = 'your_bot_token'

BOT_TOKEN = ''

# Member Tracking spreadsheet IDs
MEMBER_TRACKING_SPREADSHEET_ID = ''

# Boss Parties spreadsheet IDs
BOSS_PARTIES_SPREADSHEET_ID = ''
BOSS_PARTIES_SHEET_ID_MEMBERS = 0

# Grove submissions spreadsheet IDs
MEMBER_ACTIVITY_SPREADSHEET_ID = ''
MEMBER_ACTIVITY_SHEET_ID_ABSENCES = 0
MEMBER_ACTIVITY_SHEET_ID_BIRTHDAYS = 0

# Discord IDs
GROVE_GUILD_ID = 0

GROVE_CHANNEL_ID_ANNOUNCEMENTS = 0
GROVE_CHANNEL_ID_BOSSING_PARTIES = 0
GROVE_CHANNEL_ID_MEMBER_ACTIVITY = 0
GROVE_CHANNEL_ID_GENERAL = 0

GROVE_ROLE_ID_BIRTHDAY = 0
GROVE_ROLE_ID_AWAY = 0
GROVE_ROLE_ID_JUNIOR = 0
GROVE_ROLE_ID_SPIRIT = 0
GROVE_ROLE_ID_TREE = 0
GROVE_ROLE_ID_SAPLING = 0
GROVE_ROLE_ID_MOSS = 0
GROVE_ROLE_ID_GROVE = 0
GROVE_ROLE_ID_GUEST = 0
