BOT_TOKEN = 'bot token'

# Member Tracking spreadsheet IDs
MEMBER_TRACKING_SPREADSHEET_ID = 'member tracking spreadsheet id'

# Boss Parties spreadsheet IDs
BOSS_PARTIES_SPREADSHEET_ID = 'boss parties spreadsheet id'
BOSS_PARTIES_SHEET_ID_MEMBERS = 1234

# Discord Data spreadsheet IDs
DISCORD_DATA_SPREADSHEET_ID = 'discord data spreadsheet id'

# Discord IDs
GROVE_GUILD_ID = 1234

GROVE_CHANNEL_ID_ANNOUNCEMENTS = 1234
GROVE_CHANNEL_ID_BOSS_PARTY_LIST = 1234
GROVE_CHANNEL_ID_MODLOG = 1234

GROVE_ROLE_ID_GROVE = 1234
GROVE_ROLE_ID_JUNIOR = 1234
GROVE_ROLE_ID_SPIRIT = 1234
GROVE_ROLE_ID_TREE = 1234
GROVE_ROLE_ID_SAPLING = 1234
GROVE_ROLE_ID_MOSS = 1234
GROVE_ROLE_ID_GUEST = 1234
