BOT_TOKEN = ''

# Member Tracking spreadsheet IDs
MEMBER_TRACKING_SPREADSHEET_ID = ''

# Boss Parties spreadsheet IDs
BOSS_PARTIES_SPREADSHEET_ID = ''
BOSS_PARTIES_SHEET_ID_MEMBERS = 0

# Grove submissions spreadsheet IDs
GROVE_SUBMISSIONS_SPREADSHEET_ID = ''
GROVE_SUBMISSIONS_SHEET_ID_ABSENCES = 0
GROVE_SUBMISSIONS_SHEET_ID_BIRTHDAYS = 0

# Discord IDs
GROVE_GUILD_ID = 0

GROVE_CHANNEL_ID_ANNOUNCEMENTS = 0
GROVE_CHANNEL_ID_BOSSING_PARTIES = 0
GROVE_CHANNEL_ID_GROVE_SUBMISSIONS = 0

GROVE_ROLE_ID_AWAY = 0
GROVE_ROLE_ID_JUNIOR = 0
GROVE_ROLE_ID_SPIRIT = 0
GROVE_ROLE_ID_TREE = 0
GROVE_ROLE_ID_SAPLING = 0
GROVE_ROLE_ID_MOSS = 0
GROVE_ROLE_ID_GROVE = 0
GROVE_ROLE_ID_GUEST = 0
